### ISSUE TITLE
Running launcher from GitHub code

### ISSUE THREAD

**Issue by WoodyPWX** [andymanic/OSRTT#11]
Hello there,

I'm using OSRTT source code from GitHub, main branch.
If I open OSRTT Launcher.sln in both VS2019 (or VS2022) and compile, it fails on this:

Build started...
1>------ Build started: Project: OSRTT Launcher, Configuration: Debug Any CPU ------
1>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(3476,5): error MSB3322: Unable to get MD5 checksum for the key file "OSRTT Launcher_1_TemporaryKey.pfx". Could not find file 'C:\Temp\OSRTT\OSRTT Launcher\OSRTT Launcher\OSRTT Launcher_1_TemporaryKey.pfx'.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

Solution Explorer is showing these .pfx files missing:
![image](https://github.com/andymanic/OSRTT/assets/8375403/5a0c4b01-2f53-411b-acab-9773b1ea7741)

If I disable this signing:
![image](https://github.com/andymanic/OSRTT/assets/8375403/8e011c24-88cd-432b-b733-211c5934b898)

I can compile and start the launcher, but it never detects my OSRTT PRO unit, unlike your prebuilt version:
![image](https://github.com/andymanic/OSRTT/assets/8375403/8ff657c3-065b-4208-a297-b2930f5f9dff)

The VS output window is spamming: The system cannot find the path specified.

Regards,
Tomas

**Comment by WoodyPWX** [comment]
I think it's trying to run this:
![image](https://github.com/andymanic/OSRTT/assets/8375403/df18dd76-6ee6-427f-a71b-c39a9670c922)
so I've set correct working directory for debugging into directory with your downloaded build, including that file, so it's all good now :)

**Comment by andymanic** [comment]
You beat me to it! It uses the arduino CLI to detect which COM port to connect with so needs the program in the correct directory. As for the key files, I forgot they'd be linked in the SLN. Disabling signing or generating your own key is the fix and again you've beat me there.

**Comment by WoodyPWX** [comment]
Thanks for the clarification!
