### ISSUE TITLE
FwFlashTool bricked my device

### ISSUE THREAD

**Issue by WoodyPWX** [andymanic/OSRTT#9]
Hello there,

After I flashed my new OSRTT PRO by the fw flash tool (4.3 package), it's no longer showing anything. Display is black, LED is red.
OSRTT Launcher sees the device connected, but reports these in a USB port where it worked fine before flashing:
![image](https://github.com/andymanic/OSRTT/assets/8375403/89ae0b3a-a1c0-4bff-95dd-eb44c369d26f)
![image](https://github.com/andymanic/OSRTT/assets/8375403/00c800cf-10d7-45d0-83e1-4e3d4fbae58c)
I probably did something wrong in the flashing tool. I thought I should flash both "OSRTT" and "PRO", so I click both buttons. They both end up "successful". Flashing OSRTT is showing the text bellow.

Regards,
Tomas

OSRTT FW VERSION: 2.9
PRO FW VERSION: 1.4

Sketch uses 33720 bytes (6%) of program storage space. Maximum is 507904 bytes.

Device       : ATSAMD51x19
Version      : v1.1 [Arduino:XYZ] Jan 15 2022 11:54:42
Address      : 0x0
Pages        : 1024
Page Size    : 512 bytes
Total Size   : 512KB
Planes       : 1
Lock Regions : 32
Locked       : none
Security     : false
BOD          : false
BOR          : true
Write 35536 bytes to flash (70 pages)

[                              ] 0% (0/70 pages)
[===                           ] 11% (8/70 pages)
[======                        ] 22% (16/70 pages)
[==========                    ] 34% (24/70 pages)
[=============                 ] 45% (32/70 pages)
[=================             ] 57% (40/70 pages)
[====================          ] 68% (48/70 pages)
[========================      ] 80% (56/70 pages)
[===========================   ] 91% (64/70 pages)
[==============================] 100% (70/70 pages)
Done in 0.510 seconds
Verify 35536 bytes of flash

[=                             ] 4% (3/70 pages)
[=                             ] 5% (4/70 pages)
[==                            ] 7% (5/70 pages)
[==                            ] 8% (6/70 pages)
[===                           ] 10% (7/70 pages)
[===                           ] 11% (8/70 pages)
[===                           ] 12% (9/70 pages)
[====                          ] 14% (10/70 pages)
[====                          ] 15% (11/70 pages)
[=====                         ] 17% (12/70 pages)
[=====                         ] 18% (13/70 pages)
[======                        ] 20% (14/70 pages)
[======                        ] 21% (15/70 pages)
[======                        ] 22% (16/70 pages)
[=======                       ] 24% (17/70 pages)
[=======                       ] 25% (18/70 pages)
[========                      ] 27% (19/70 pages)
[========                      ] 28% (20/70 pages)
[=========                     ] 30% (21/70 pages)
[=========                     ] 31% (22/70 pages)
[=========                     ] 32% (23/70 pages)
[==========                    ] 34% (24/70 pages)
[==========                    ] 35% (25/70 pages)
[===========                   ] 37% (26/70 pages)
[===========                   ] 38% (27/70 pages)
[============                  ] 40% (28/70 pages)
[============                  ] 41% (29/70 pages)
[============                  ] 42% (30/70 pages)
[=============                 ] 44% (31/70 pages)
[=============                 ] 45% (32/70 pages)
[==============                ] 47% (33/70 pages)
[==============                ] 48% (34/70 pages)
[===============               ] 50% (35/70 pages)
[===============               ] 51% (36/70 pages)
[===============               ] 52% (37/70 pages)
[================              ] 54% (38/70 pages)
[================              ] 55% (39/70 pages)
[=================             ] 57% (40/70 pages)
[=================             ] 58% (41/70 pages)
[==================            ] 60% (42/70 pages)
[==================            ] 61% (43/70 pages)
[==================            ] 62% (44/70 pages)
[===================           ] 64% (45/70 pages)
[===================           ] 65% (46/70 pages)
[====================          ] 67% (47/70 pages)
[====================          ] 68% (48/70 pages)
[=====================         ] 70% (49/70 pages)
[=====================         ] 71% (50/70 pages)
[=====================         ] 72% (51/70 pages)
[======================        ] 74% (52/70 pages)
[======================        ] 75% (53/70 pages)
[=======================       ] 77% (54/70 pages)
[=======================       ] 78% (55/70 pages)
[========================      ] 80% (56/70 pages)
[========================      ] 81% (57/70 pages)
[========================      ] 82% (58/70 pages)
[=========================     ] 84% (59/70 pages)
[=========================     ] 85% (60/70 pages)
[==========================    ] 87% (61/70 pages)
[==========================    ] 88% (62/70 pages)
[===========================   ] 90% (63/70 pages)
[===========================   ] 91% (64/70 pages)
[===========================   ] 92% (65/70 pages)
[============================  ] 94% (66/70 pages)
[============================  ] 95% (67/70 pages)
[============================= ] 97% (68/70 pages)
[============================= ] 98% (69/70 pages)
[==============================] 100% (70/70 pages)
Verify successful
Done in 0.169 seconds

**Comment by andymanic** [comment]
Hi there - so I think what's happened is it has flashed the non-pro device firmware, hence the display not showing anything and you're getting the USB voltage errors that are only present on the original device. Can you try clicking just the "flash pro" button (with the main OSRTT Launcher program closed) and see if that restores it? If it doesn't, please do copy the output like you've done here so I can confirm what's wrong.

**Comment by WoodyPWX** [comment]
I was trying that before, but "PRO" button flashing is not outputting anything. All I get is
![image](https://github.com/andymanic/OSRTT/assets/8375403/3c34fb0a-882c-427b-bf0e-8229c74752b2)

**Comment by WoodyPWX** [comment]
The new flash tool is about 1KB bigger, but it behaves exactly the same. No text output while flashing PRO and then the "updated successfully" button. Device still not fixed. Regarding my forced flashing, I will not use that again. At least you know the tool should be more foolproof :)

**Comment by andymanic** [comment]
Ok. Can you disconnect and reconnect the device? Is the LED inside still red? If it is, I suspect you might need to open the unit up to press the reset button on the microcontroller board. It's two 2.5mm Allen/hex key screws on the bottom and the reset button is basically in the middle of the board. The board should be plugged in and you might need to press the reset button twice in quick succession until the built in LED is either green or purple. I'm hopeful unplugging and reconnecting will solve it though!

**Comment by WoodyPWX** [comment]
Reconnecting didn't help, but after I opened the unit up, I realized the LED color is not red but actually purple. Double press of the reset button makes it red and then immediately green and the Launcher is not complaining anymore. The display is still black though and after disconnecting from USB and reconnecting, the LED is again purple, requiring reset.

**Comment by andymanic** [comment]
Ah ok, that's good. The board is definitely in a recoverable state. Can you check that there's a file called "OSRTT_Pro_Code_1.5.ino.bin" in "C:\OSRTT Launcher\arduinoCLI"? 

If there is, can you also check what COM port the device is using - you can see that either in Device Manager under "Ports", or even better open powershell and run "& "C:\OSRTT Launcher\arduinoCLI\arduino-cli.exe" board list"

If there isn't, you can grab it from the repo and place it in that folder - [file](https://github.com/andymanic/OSRTT/releases/download/4.3/OSRTT_Pro_Code_1.5.ino.bin)

Then run "& "C:\OSRTT Launcher\arduinoCLI\arduino-cli.exe" upload --port COM3 --fqbn adafruit:samd:adafruit_itsybitsy_m4 -i "C:\OSRTT Launcher\arduinoCLI\OSRTT_Pro_Code_1.5.ino.bin""

That should flash the board manually and give you the full output (and therefore any error messages).
